server:
  port: 8080
  servlet:
    context-path: /vm
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/yb_carb?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: wisesoft
      initial-size: 5
      max-active: 100
      max-wait: 20
      min-idle: 10
      validationQuery: SELECT 1 FROM DUAL
      db-type: mysql
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jpa:
    show-sql: true